#!/usr/bin/env python3
"""
Write .streamlit/secrets.toml for the dashboard, deriving it from the dbt
profile that already works.

WHY DERIVE IT INSTEAD OF ASKING AGAIN
scripts/set_dbt_profile.py already generated the key pair, registered the public
half with Snowflake and wrote ~/.dbt/profiles.yml at mode 600. Every value the
dashboard needs is in that file. Prompting for them a second time would mean the
passphrase -- which was generated precisely so that it never had to be typed --
gets typed, and gets a second chance to end up in a shell history file or a
terminal scrollback buffer. Reading it from disk and writing it to disk costs it
nothing.

WHAT THIS DOES NOT DO
It does not touch Snowflake, it does not create a key, and it does not read
anything from this repository. If ~/.dbt/profiles.yml is missing or has no
key-pair entry, the fix is to run scripts/set_dbt_profile.py, not this.

WHERE THE OUTPUT GOES
<repo>/.streamlit/secrets.toml, mode 600, which is where Streamlit looks when
the app is launched from the repository root. That path is ignored twice over by
.gitignore -- once by the `secrets*` pattern and once by an explicit line -- and
the pre-commit secret scan runs on top of that.

Usage:  python scripts/set_dashboard_profile.py
"""

import json
import os
import stat
import sys

import yaml

PROFILE_NAME = "market_data"
PROFILES = os.path.expanduser("~/.dbt/profiles.yml")
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(REPO_ROOT, ".streamlit")
OUT_PATH = os.path.join(OUT_DIR, "secrets.toml")

# The dashboard reads the marts layer. dbt's own default schema is staging,
# because that is where dbt builds first; overriding it here keeps an
# unqualified query in the app from silently resolving against the wrong schema.
DASHBOARD_SCHEMA = "marts"

REQUIRED = ["account", "user", "role", "warehouse", "database", "private_key_path"]


def fail(message):
    print(f"ERROR: {message}", file=sys.stderr)
    sys.exit(1)


def load_output():
    if not os.path.exists(PROFILES):
        fail(f"{PROFILES} does not exist. Run scripts/set_dbt_profile.py first.")

    with open(PROFILES) as handle:
        profiles = yaml.safe_load(handle) or {}

    profile = profiles.get(PROFILE_NAME)
    if not profile:
        fail(f"{PROFILES} has no '{PROFILE_NAME}' profile.")

    target = profile.get("target")
    outputs = profile.get("outputs") or {}
    output = outputs.get(target)
    if not output:
        fail(f"{PROFILES} has no output named '{target}' under '{PROFILE_NAME}'.")

    missing = [key for key in REQUIRED if not output.get(key)]
    if missing:
        fail(
            "the dbt profile is missing "
            + ", ".join(missing)
            + ". Run scripts/set_dbt_profile.py to rebuild it."
        )

    if not os.path.exists(os.path.expanduser(output["private_key_path"])):
        fail(
            "the private key named in the dbt profile does not exist at "
            + output["private_key_path"]
        )

    return output


def toml_string(value):
    # A JSON string and a TOML basic string share the same escaping rules, and
    # json.dumps is in the standard library, so the quoting here is done by
    # something that has been tested rather than by an f-string.
    return json.dumps(str(value))


def main():
    output = load_output()

    lines = [
        "# Generated by scripts/set_dashboard_profile.py. Do not commit.",
        "#",
        "# Streamlit reads this when the app is launched from the repository",
        "# root. The deployed copy of these values lives in Streamlit Community",
        "# Cloud's own secrets store and is entered there by hand, with",
        "# private_key_pem in place of private_key_path -- the cloud runner has",
        "# no ~/.snowflake to read from.",
        "",
        "[snowflake]",
        f'account = {toml_string(output["account"])}',
        f'user = {toml_string(output["user"])}',
        f'role = {toml_string(output["role"])}',
        f'warehouse = {toml_string(output["warehouse"])}',
        f'database = {toml_string(output["database"])}',
        f"schema = {toml_string(DASHBOARD_SCHEMA)}",
        f'private_key_path = {toml_string(output["private_key_path"])}',
    ]

    passphrase = output.get("private_key_passphrase")
    if passphrase:
        lines.append(f"private_key_passphrase = {toml_string(passphrase)}")

    os.makedirs(OUT_DIR, exist_ok=True)
    os.chmod(OUT_DIR, stat.S_IRWXU)

    # Create the file with the right permissions before anything is written to
    # it, rather than writing it world-readable and narrowing afterwards.
    #
    # ...and then chmod it anyway, because the mode argument below is a
    # CREATION mode. If the path already exists, os.open ignores it completely
    # and the file keeps whatever permissions it already had. That is not
    # hypothetical: on 2026-09-11 this script wrote a passphrase into a
    # leftover 0644 file and reported 0o644, which is how the bug was found.
    # A umask of 027 or 077 would also have narrowed the creation mode without
    # anyone noticing until it mattered.
    flags = os.O_WRONLY | os.O_CREAT | os.O_TRUNC
    handle = os.open(OUT_PATH, flags, stat.S_IRUSR | stat.S_IWUSR)
    with os.fdopen(handle, "w") as out:
        out.write("\n".join(lines) + "\n")

    os.chmod(OUT_PATH, stat.S_IRUSR | stat.S_IWUSR)

    # Refuse to report success on a file anyone else on this machine can read.
    written_mode = os.stat(OUT_PATH).st_mode & 0o777
    if written_mode != 0o600:
        fail(
            f"{OUT_PATH} is mode {oct(written_mode)}, not 0o600. It holds the "
            "private key passphrase. Fix the permissions before using it."
        )

    # Report what was written without reporting any of it. The account, user and
    # role are not secrets, but printing them here would put them in a terminal
    # buffer for no gain, and the passphrase is never printed at all.
    print(f"Wrote {OUT_PATH}")
    print(f"  mode              {oct(os.stat(OUT_PATH).st_mode & 0o777)}")
    values = sum(1 for line in lines if " = " in line)
    print(f"  keys              {values} values under [snowflake]")
    print(f"  passphrase        {'present' if passphrase else 'not set'} (not shown)")
    print(f"  private key       {output['private_key_path']}")
    print()
    print("Next:  streamlit run dashboard/app.py")


if __name__ == "__main__":
    main()
